In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.functional as F
import math

In [4]:
l=4
d_k=8
d_v=8
q=np.random.randn(l,d_k)
k=np.random.randn(l,d_k)
v=np.random.randn(l,d_v)

In [5]:
print("Q\n",q)
print("Q\n",k)
print("Q\n",v)

Q
 [[ 0.44401731 -0.42598058 -0.74618823  0.68800076  0.34912559  0.65861128
   1.57016608  0.79206744]
 [-0.01436775  1.58717416  0.12813724 -1.76301275  1.0837585   1.14916903
  -1.74193789  2.19906735]
 [-0.91518929 -0.53698372  0.78439258  0.50790842 -0.60848266 -1.98360336
   1.04370414  0.85808349]
 [ 0.71384061 -1.92270571  0.25042242 -0.04146462 -0.92302799  0.94420321
  -0.80984849  2.59172233]]
Q
 [[ 0.10894308  0.85630305  0.47196018  0.03892268  0.72058459 -2.23761421
  -1.20959174 -0.92567552]
 [ 1.12864295  0.37322868  1.3425872   0.65673787 -1.01449411  0.88344755
   0.46494404  1.59229199]
 [-0.92931934  0.40092991  0.11305415 -1.19326872  0.10211868 -0.50978238
   1.03277144 -0.33564192]
 [ 0.48172587  0.894356    1.21899109  0.17269117 -1.38833474 -0.17152753
   0.45868256 -0.1678526 ]]
Q
 [[-1.74885045e-02 -1.50975818e+00 -2.09953900e+00 -1.51987565e+00
   1.97379814e+00 -5.08908279e-01  2.86762494e+00  1.22555237e-01]
 [ 5.48068028e-01 -4.99533972e-01  8.12068903e-0

## Self-Attention

In [6]:
np.matmul(q,k.T)

array([[-4.49638896,  2.0110669 , -0.43307624, -0.96828474],
       [-0.36965512,  2.19777864, -0.2443448 , -1.60553058],
       [ 1.77375993,  0.86981451,  1.85678552,  1.64247145],
       [-5.64946541,  5.91784975, -3.63834199, -0.76458148]])

In [7]:
q.var(),k.var(),np.matmul(q,k.T).var()

(1.2966137648319682, 0.7909284788389416, 7.723335798757704)

In [8]:
scaled=np.matmul(q,k.T)/math.sqrt(d_k)

In [9]:
scaled.var()

0.965416974844713

In [14]:
scaled.shape

(4, 4)

## Masking

In [21]:
mask=np.tril(np.ones((l,l)))

In [22]:
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [24]:
mask[mask==0]=-np.infty
mask[mask==1]=0

In [25]:
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [27]:
l=scaled+mask

In [30]:
def softmax(x):
    return (np.exp(x).T/np.sum(np.exp(x),axis=-1)).T
    

In [31]:
attention=softmax(scaled+mask)

In [32]:
attention

array([[1.        , 0.        , 0.        , 0.        ],
       [0.28746562, 0.71253438, 0.        , 0.        ],
       [0.36281394, 0.26356425, 0.37362182, 0.        ],
       [0.01462415, 0.8733513 , 0.02977633, 0.08224821]])

In [34]:
self_attn=np.matmul(attention,v)
self_attn

array([[-0.0174885 , -1.50975818, -2.099539  , -1.51987565,  1.97379814,
        -0.50890828,  2.86762494,  0.12255524],
       [ 0.38548997, -0.7899387 , -0.02491826, -0.91955252,  0.49597394,
        -0.66059436, -0.58459193,  0.57555986],
       [ 0.13847638,  0.03698182, -0.78086282, -0.74272224, -0.09628066,
        -0.62763135,  0.84446503,  0.53356229],
       [ 0.56148476, -0.48885761,  0.70083232, -0.59643445,  0.01121175,
        -0.83009301, -1.61414221,  0.77876855]])

In [35]:
ls

Self_Attention.ipynb


In [42]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /Users/debruppaul/Transformer_Architecture/.git/


In [ ]:
! 